apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws4-app
  template:
    metadata:
      labels:
        app: ws4-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ws4-app
        image: nicolass03/dsworkshop4
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: ws4-app
spec:
  ports:
  - port: 6379
  selector:
    app: ws4-app
