http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  apppay:
    host: localhost
    paths: ['/pay','/pay/*']
serviceEndpoints:
  apppay:
   url: 'http://loadbalancer/pay/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - apppay
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: apppay 
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false
