http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  appconfig:
    host: localhost
    paths: ['/config','/config/*']
  apppay:
    host: localhost
    paths: ['/pay','/pay/*']
serviceEndpoints:
  appconfig:
    url: 'http://loadbalancer/config/'
  apppay:
    url: 'http://loadbalancer/pay/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - appconfig
      - apppay
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth: 
      - proxy:
          - action:
              serviceEndpoint: appconfig 
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false
