kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    project: chapter3
    service: web
  ports:
   - protocol: TCP
     name: http
     port: 80
     targetPort: 8000