apiVersion: v1
kind: Pod
metadata:
  name: app-python
  labels:
    project: workshop4
    service: web
    version: "0.1"
    app: mypyapp
spec:
  containers:
  - name: app
    image: mypyapp:local
    imagePullPolicy: Never