apiVersion: v1
kind: Pod
metadata:
  name: mypyapp
  labels:
    project: workshop4
    service: web
    version: "0.1"
    app: mypyapp
spec:
  containers:
  - name: mypyapp 
    image: mypyapp:local
    imagePullPolicy: Never
    ports:
      - containerPort: 8000