apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      project: workshop4
    matchExpressions:
      - {key: version, operator: In, values: ["0.1", "0.2"]}
  template:
    metadata:
      name: mypyapp
      labels:
        project: workshop4
        service: web
        version: "0.1"
    spec:
      containers:
      - name: mypyapp
        image: mypyapp:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000