apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: workshop4
    matchExpressions:
      - {key: version, operator: In, values: ["0.1", "0.2"]}
  template:
    metadata:
      name: app
      labels:
        project: workshop4
        service: web
        version: "0.1"
    spec:
      containers:
      - name: app
        image: mypyapp:local
